version: '3.8'
services:

  # Backend
  app:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables"
    container_name: smartbrain-back-app
    image: tmssd/smartbrain-back-app:latest
    build: ./
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379

  # PostgreSQL
  postgres:
    container_name: smartbrain-back-postgres
    image: tmssd/smartbrain-back-postgres:latest
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/smart-brain
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: smartbrain-back-redis
    image: redis
    ports:
      - "6379:6379"
