name: Build Container for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push smartbrain-be-app
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: tmssd/smartbrain-be-app:latest
      -
        name: Build and push smartbrain-be-postgres
        uses: docker/build-push-action@v3
        with:
          context: ./postgres
          push: true
          file: ./postgres/Dockerfile
          tags: tmssd/smartbrain-be-postgres:latest
      # -
      #   name: Build Docker Images
      #   run: |
      #     docker build --tag tmssd/smartbrain-be-app:latest . && \
      #     docker build --tag tmssd/smartbrain-be-postgres:latest --file ./postgres/Dockerfile ./postgres
      # -
      #   name: Push Docker Images to Docker Hub
      #   run: |
      #     docker image push tmssd/smartbrain-be-app:latest && \
      #     docker image push tmssd/smartbrain-be-postgres:latest
