name: Build Container for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     file: Dockerfile
      #     tags: tmssd/smartbrain-back:latest
      -
        name: Build Docker Images
        run: |
          docker build --tag tmssd/smartbrain-back-app:latest . && \
          docker build --tag tmssd/smartbrain-back-postgres:latest --file ./postgres/Dockerfile
      -
        name: Push Docker Images to Docker Hub
        run: |
          docker image push tmssd/smartbrain-back-app:latest && \
          docker image push tmssd/smartbrain-back-postgres:latest
